-- MySQL Script generated by MySQL Workbench
-- Wed Feb  4 09:21:30 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniblog` DEFAULT CHARACTER SET latin1 ;
USE `miniblog` ;

-- -----------------------------------------------------
-- Table `miniblog`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`account` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `firstname` VARCHAR(32) NOT NULL,
  `lastname` VARCHAR(32) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT '2015-01-01 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `miniblog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`posts` (
  `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `content` VARCHAR(2048) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT '2015-01-01 00:00:00',
  `status` TINYINT(1) NOT NULL,
  `account_id` INT(16) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_account` (`account_id` ASC),
  CONSTRAINT `fk_posts_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `miniblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`comments` (
  `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(254) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT '2015-01-01 00:00:00',
  `account_id` INT(16) UNSIGNED NOT NULL,
  `posts_id` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_account` (`account_id` ASC),
  INDEX `fk_comments_posts` (`posts_id` ASC),
  CONSTRAINT `fk_comments_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`),
  CONSTRAINT `fk_comments_posts`
    FOREIGN KEY (`posts_id`)
    REFERENCES `miniblog`.`posts` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `miniblog`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`token` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `access_token` VARCHAR(100) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired_at` TIMESTAMP NOT NULL DEFAULT '2015-01-01 00:00:00',
  `account_id` INT(16) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `access_token` (`access_token` ASC),
  INDEX `fk_token_account` (`account_id` ASC),
  CONSTRAINT `fk_token_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from account;
select * from posts where status =1 order by create_at desc limit 10;
select * from comments;
select * from token;

delete from account where id = 5;

delete from posts where id= 25;


