-- MySQL Script generated by MySQL Workbench
-- Tue Jan 20 10:27:32 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `miniblog` ;

-- -----------------------------------------------------
-- Table `miniblog`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`account` (
  `id` INT(11) UNSIGNED NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `create_at` TIMESTAMP NOT NULL,
  `modified_at` TIMESTAMP NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lastname` (),
  INDEX `firstname` (),
  INDEX `username` ())
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`posts` (
  `id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `create_at` TIMESTAMP NOT NULL,
  `modified_at` TIMESTAMP NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `id_acc` INT(11) UNSIGNED NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `title` (),
  INDEX `create_at` (),
  INDEX `fk_posts_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_posts_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`comments` (
  `id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(500) NOT NULL,
  `create_at` TIMESTAMP NOT NULL,
  `modified_at` TIMESTAMP NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `id_acc` INT(11) UNSIGNED NOT NULL,
  `id_posts` INT(11) UNSIGNED NOT NULL,
  `posts_id` INT(11) UNSIGNED NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `posts_id`, `account_id`),
  INDEX `title` (),
  INDEX `create_at` (),
  INDEX `fk_comments_posts_idx` (`posts_id` ASC),
  INDEX `fk_comments_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_comments_posts`
    FOREIGN KEY (`posts_id`)
    REFERENCES `miniblog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`token` (
  `access_token` VARCHAR(200) NOT NULL,
  `create_at` VARCHAR(45) NOT NULL,
  `expired_at` VARCHAR(45) NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`access_token`, `account_id`),
  INDEX `fk_token_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_token_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
