-- MySQL Script generated by MySQL Workbench
-- Tue Jan 20 09:45:34 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `miniblog` ;

-- -----------------------------------------------------
-- Table `miniblog`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`account` (
  `id` INT(11) UNSIGNED NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(20) NULL,
  `lastname` VARCHAR(20) NULL,
  `image` VARCHAR(50) NULL,
  `gender` TINYINT(1) NULL,
  `email` VARCHAR(50) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `firstname` (),
  INDEX `lastname` (),
  INDEX `email` ())
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`posts` (
  `id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `modified_date` TIMESTAMP NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `id_acc` INT(11) UNSIGNED NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `title` (),
  INDEX `create_date` (),
  INDEX `fk_posts_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_posts_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`comments` (
  `id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `modified_date` TIMESTAMP NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `id_acc` INT(11) NOT NULL,
  `id_posts` INT(11) NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  `posts_id` INT(11) UNSIGNED NOT NULL,
  `posts_account_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `account_id`, `posts_id`, `posts_account_id`),
  INDEX `fk_comments_account1_idx` (`account_id` ASC),
  INDEX `title` (`posts_id` ASC, `posts_account_id` ASC),
  INDEX `create_date` (),
  CONSTRAINT `fk_comments_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `miniblog`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id` , `posts_account_id`)
    REFERENCES `miniblog`.`posts` (`id` , `account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`token` (
  `access_token` VARCHAR(200) NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `expired_date` TIMESTAMP NOT NULL,
  `id_acc` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`access_token`, `id_acc`),
  INDEX `fk_token_account1_idx` (`id_acc` ASC),
  CONSTRAINT `fk_token_account1`
    FOREIGN KEY (`id_acc`)
    REFERENCES `miniblog`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
